In [24]:
import numpy as np
import sys

In [8]:

a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:

b = np.array([[9,8,7,],[6,5,4]])
print(b)




[[9 8 7]
 [6 5 4]]


In [9]:
a.ndim

1

In [10]:
a.shape

(3,)

In [11]:
# get a type

In [ ]:
#Get type
a.dtype

dtype('int64')

In [ ]:
#Get size
a.itemsize

8

In [16]:
# total size
a.nbytes

24

Accessing /Changing specific elements, rwa, columns,etc

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get row and column
a[1][5]

np.int64(13)

In [30]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [36]:
# Gettomg a little more fancy
a[0,1:-1:2]

array([2, 4, 6])

In [38]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [46]:
b =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [50]:
# get a specific element (work outside in)
b[0,1,1]

np.int64(4)

In [53]:
# replace
b[:,1,:] = [[9,9,9],[8,9]]
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Initializing Different Types of Arrays

<!-- All 0s matrix -->
np.zeros(2,3,3,2)

In [56]:
# <!-- All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [61]:
np.ones((4,2,2),dtype='int'
        )

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [63]:
# Any other number
np.full((2,2),43)

array([[43, 43],
       [43, 43]])

In [65]:
# Any other number like full
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
# random decimal numbers
np.random.rand(4,2)

array([[0.09246499, 0.79073031],
       [0.62830408, 0.08803537],
       [0.72190555, 0.53529807],
       [0.92866878, 0.41277628]])

In [74]:
# Random integer values
np.random.randint((3,8), size=(3,2))


array([[2, 4],
       [2, 4],
       [1, 0]])

In [76]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
# Repeat an error
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [95]:
output = np.ones((5,5))
z  = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z

print(output)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be carefull when copying

In [102]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


Mathematics

In [105]:
a = np.array([1,2,3,4])
print(a)
a+2
print(a)

[1 2 3 4]
[1 2 3 4]


In [106]:
a+2


array([3, 4, 5, 6])

<!-- All 0s matrix -->
np.zeros(2,3,3,2)

In [107]:
a-2

array([-1,  0,  1,  2])

In [108]:
a*2

array([2, 4, 6, 8])

In [109]:
b = np.array([1,0,1,0])


In [110]:
a+b

array([2, 2, 4, 4])

In [111]:
a**2

array([ 1,  4,  9, 16])

np.cos(a)