Intorduction to Tensors

In [2]:
print("Hello I'm excited to learn PyTorch!")
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

Hello I'm excited to learn PyTorch!
2.9.1


PyTorch Tensors are createdusing 'torch.Tensor()'


In [3]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python tensor int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random Tensors

In [17]:
#Creating a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7739, 0.8715, 0.7865, 0.9395],
        [0.1589, 0.3441, 0.2385, 0.5679],
        [0.3578, 0.7284, 0.2349, 0.9489]])

In [18]:
#creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size =(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
rand_tensor = torch.rand(3,5
)
rand_tensor

tensor([[0.8688, 0.1924, 0.8775, 0.4303, 0.6078],
        [0.6950, 0.2151, 0.4154, 0.3933, 0.6074],
        [0.7568, 0.6017, 0.8764, 0.6938, 0.6971]])

In [20]:
random_tensor = torch.rand(4,7,4)
random_tensor

tensor([[[0.2599, 0.1746, 0.9131, 0.0957],
         [0.9473, 0.4179, 0.2818, 0.8243],
         [0.8231, 0.3227, 0.3188, 0.1226],
         [0.2443, 0.0438, 0.6886, 0.3838],
         [0.0036, 0.2170, 0.3467, 0.3529],
         [0.3411, 0.2874, 0.1352, 0.6957],
         [0.8348, 0.6133, 0.6524, 0.4742]],

        [[0.8816, 0.6350, 0.1950, 0.1190],
         [0.7986, 0.7237, 0.2007, 0.3380],
         [0.8333, 0.7001, 0.1867, 0.0429],
         [0.0540, 0.0881, 0.6321, 0.9248],
         [0.7839, 0.0582, 0.2558, 0.0093],
         [0.7643, 0.8964, 0.4443, 0.4764],
         [0.3425, 0.8353, 0.7341, 0.9805]],

        [[0.1399, 0.6209, 0.1441, 0.7256],
         [0.7956, 0.5190, 0.1322, 0.1103],
         [0.6981, 0.3218, 0.4326, 0.4050],
         [0.1774, 0.9537, 0.1334, 0.2485],
         [0.6688, 0.2962, 0.8580, 0.2932],
         [0.0875, 0.9565, 0.2013, 0.8968],
         [0.5806, 0.2967, 0.6999, 0.6221]],

        [[0.1949, 0.5849, 0.7337, 0.2028],
         [0.6435, 0.0452, 0.3769, 0.8593],
     

Create a tensor of all zeroes

In [21]:
zeroes  =torch.zeros(3,5)
zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Create a tensor of all ones

In [22]:
ones  =torch.ones(3,5)
ones


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [24]:
#Using torch.range()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#Creating Tensor-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Float 32 Tensor

In [26]:
float32_tensor =torch.tensor([3.0,6.0,9.0],
                            dtype = None,
                            device = "mps",
                            requires_grad = False)
float32_tensor

tensor([3., 6., 9.], device='mps:0')

In [27]:
float32_tensor.dtype

torch.float32

In [28]:
float16_tensor = float32_tensor.type(torch.half)

In [29]:
float16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [30]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
float_32_tensor = torch.tensor([3,6,9], dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float16_tensor* float32_tensor

tensor([ 9., 36., 81.], device='mps:0')

In [34]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [35]:
#Getting information form tensors
#Tensors are not dtype or device 

In [36]:
#Createa a tensor
tensor1 = torch.rand([3,4])
tensor1

tensor([[0.8510, 0.0361, 0.3851, 0.6138],
        [0.3473, 0.5250, 0.2568, 0.6912],
        [0.7283, 0.3763, 0.7402, 0.6335]])

In [37]:
#Finding out details about tensor1
print(tensor1)
print(f"Datatype of tensor is {tensor1.dtype}")
print(f" Shape of tensor is {tensor1.shape}")
print(f"Device is {tensor1.device}")


tensor([[0.8510, 0.0361, 0.3851, 0.6138],
        [0.3473, 0.5250, 0.2568, 0.6912],
        [0.7283, 0.3763, 0.7402, 0.6335]])
Datatype of tensor is torch.float32
 Shape of tensor is torch.Size([3, 4])
Device is cpu


Manipulating Tensers (tensor operations)

addition/
subtraction/
multiplication/
division/
matrix multiplication

In [38]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [39]:
#Create a tensor 
#Multiplication
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [40]:
#Create a tensor 
#Subtraction
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [41]:
torch.mul(tensor,10)

tensor([10, 20, 30])

##Matrix Multiplication

There are two main ways of performing multiplication in neural network and deeplearning 

Element-wise multiplication 
Thera two main rules that performing matrix multiplication needs to satisfy
1 inner dimensions must match
3,2  3,2 will not work
2,3  3,2 will  work
3,2  2,3 will  work


Matrix Multipliaction(dot product)

In [42]:
#Element_wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
torch.matmul(tensor,tensor)

tensor(14)

In [44]:
##Matrix Multiplication
1*1+2*2+3*3


14

In [45]:
#time
value = 0
for i in range (len(tensor)):
    value  += tensor[i]*tensor[i]
print(value)

tensor(14)


One of the most common errors in deeplearning is shape error


In [46]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.8114, 0.7357, 0.8308],
        [1.0599, 0.8723, 1.0413],
        [0.9149, 0.9013, 0.9723]])

In [47]:
#Shapes for matrix multiplications 
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]
                         ])

tensor_B = torch.tensor([[7,8,9],
                         [10,11,12]
                         ])

tensor_B.shape
tensor_A.shape
torch.matmul(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

tensor_B.T 
when the shapes of tensors are mismatching 
we can use .T transpose method to handle thos problem

Finding the min, mean, max , sum , etc(tensor aggregation)


In [48]:
#Create a tensor
x = torch.arange(0,100,10)

torch.max(x)
torch.mean(x.type(torch.float32))


tensor(45.)

In [51]:
#Finding the positional min and max

#Finding the position in tensor that has the ionimum value with argmin() -> returns index

x.argmin()

tensor(0)

In [52]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
x.argmin()


tensor(0)

In [56]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
x.argmax()

tensor(9)

In [ ]:
#reshaping, stacking squeezing and unsqueezing tensors

Reshaping -- reshapes an input tensor to a defined shape


View -- Return a view of an input tensor of certain shape but keep the same memory as the original tensor

Stacking -- combine multiple tensors on top of each other (vstack) or side by side (hstack)

Squeeze -- removes all 'l' dimension to a target tensor

Unsequeeze -- add a 1 dimensiopn to a target tensor

Permute -- return aa view pf the input with dimensions permuted(Swapped) in 
 certain way

In [60]:
#Let's create a tensor 

import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
#Add a extra dimension 
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [67]:
#Change the view 
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
#changeing z changes x (because a aview of a  tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
#Stack tensors on top of each other
x_stacked  = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [85]:
#torch.squeeze () -- removes all single dimesnions from a target tensor
print(f"Previous tensor {x_reshaped}")
print(f"Previous shape {x_reshaped.shape}")


#Remove an extra dimensions form a x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New {x_squeezed}")
print(f"New shape {x_squeezed.shape}")

Previous tensor tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape torch.Size([9, 1])
New tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape torch.Size([9])


In [94]:
#torch.unsqueeze adds a single dimension to target tensor at a specific tim (dimension)
print(f"Previous target {x_squeezed}")
print(f"Previous shape {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New target {x_squeezed}")
print(f"New shape {x_squeezed.shape}")

Previous target tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape torch.Size([9])
New target tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape torch.Size([9])


In [108]:
#torch.permute -- rearranges the dimensions of a atarget tensor in a specified order
x_original = torch.rand(size =(224,224,3)) #height width chanel colour

#Permute the originial tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1)
print(f"Previous shape  {x_original}")
print(f"New shape {x_permuted.shape}")

x_original[0,0,0] = 7 
x_original



Previous shape  tensor([[[0.4571, 0.6894, 0.6690],
         [0.4361, 0.3112, 0.2038],
         [0.1942, 0.5132, 0.7347],
         ...,
         [0.1993, 0.9257, 0.1585],
         [0.0999, 0.4621, 0.0935],
         [0.1229, 0.6559, 0.1496]],

        [[0.0498, 0.4559, 0.3124],
         [0.0352, 0.6850, 0.9651],
         [0.6261, 0.9486, 0.3939],
         ...,
         [0.7015, 0.4413, 0.5323],
         [0.1468, 0.2371, 0.5166],
         [0.3177, 0.2102, 0.6957]],

        [[0.3723, 0.7575, 0.1258],
         [0.4044, 0.9989, 0.7839],
         [0.3493, 0.9919, 0.3365],
         ...,
         [0.4512, 0.9161, 0.9439],
         [0.9687, 0.3663, 0.8715],
         [0.4911, 0.8134, 0.1087]],

        ...,

        [[0.1414, 0.7196, 0.6503],
         [0.0886, 0.3930, 0.7167],
         [0.3321, 0.3076, 0.1216],
         ...,
         [0.5814, 0.5146, 0.2220],
         [0.1658, 0.1623, 0.4016],
         [0.8291, 0.9780, 0.0593]],

        [[0.0168, 0.3214, 0.5087],
         [0.7103, 0.2620, 0.512

tensor([[[7.0000e+00, 6.8939e-01, 6.6901e-01],
         [4.3609e-01, 3.1120e-01, 2.0380e-01],
         [1.9420e-01, 5.1321e-01, 7.3471e-01],
         ...,
         [1.9934e-01, 9.2573e-01, 1.5845e-01],
         [9.9906e-02, 4.6209e-01, 9.3492e-02],
         [1.2289e-01, 6.5587e-01, 1.4964e-01]],

        [[4.9810e-02, 4.5585e-01, 3.1236e-01],
         [3.5221e-02, 6.8497e-01, 9.6507e-01],
         [6.2606e-01, 9.4861e-01, 3.9388e-01],
         ...,
         [7.0149e-01, 4.4129e-01, 5.3231e-01],
         [1.4682e-01, 2.3711e-01, 5.1659e-01],
         [3.1768e-01, 2.1020e-01, 6.9574e-01]],

        [[3.7228e-01, 7.5750e-01, 1.2579e-01],
         [4.0440e-01, 9.9891e-01, 7.8385e-01],
         [3.4930e-01, 9.9189e-01, 3.3648e-01],
         ...,
         [4.5122e-01, 9.1606e-01, 9.4392e-01],
         [9.6867e-01, 3.6631e-01, 8.7152e-01],
         [4.9105e-01, 8.1336e-01, 1.0866e-01]],

        ...,

        [[1.4137e-01, 7.1959e-01, 6.5026e-01],
         [8.8581e-02, 3.9303e-01, 7.1669e-01]

Indexing

In [110]:
#create a tensor 
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [112]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
#Let's index on middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [114]:
#Let's index on most inner bracket(dim=1)
x[0][0][0]

tensor(1)

In [120]:
x[0][2][2]

tensor(9)

In [121]:
# you can also use ":" to select "all" of a target dimension
x[:,0]


tensor([[1, 2, 3]])

In [124]:
#Get all values of 0th and 1st dimensions but only index 1of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [129]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,2,:]

tensor([7, 8, 9])

PYTORCH &&& NumPy

In [136]:
#NumPy array
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.]), array([1., 2., 3., 4., 5., 6., 7.]))

In [137]:
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [138]:
#Tenosr to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [139]:
#Change the tensor , see what happens to numpy_tensor
tensor = torch.zeros(7)
tensor, numpy_tensor

(tensor([0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [140]:


torch.rand(3,3)

tensor([[0.3748, 0.9475, 0.1526],
        [0.6316, 0.9604, 0.2917],
        [0.4461, 0.3506, 0.8178]])

In [143]:
#Create two random tensors 
random_tensor_A = torch.rand(3,4)
random_tensor_B  = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A ==random_tensor_B)

tensor([[0.8176, 0.4754, 0.2268, 0.9509],
        [0.1147, 0.8300, 0.6158, 0.1926],
        [0.0234, 0.5985, 0.1041, 0.3228]])
tensor([[0.0955, 0.5727, 0.4787, 0.7902],
        [0.4280, 0.9718, 0.4469, 0.2449],
        [0.4068, 0.6311, 0.7422, 0.8120]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [148]:
#Let's make some random but reproducoble tensors 
import torch 

#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C ==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
